### ISSUE TITLE
Authorization Clarification

### ISSUE THREAD

**Issue by fbergamini** [clockify/clockify_api_docs#1]
Greetings,

I started using the Clockify API and noticed that the authorization part was not quite clear to me, as it took me some time to figure out how to properly do it.

I'd like to suggest adding a section explaining that the API key must be used with the X-Api-Key header and the token obtained with the email and password must be used with the X-Auth-Token header.

Thanks for the development of Clockify, it has been quite useful to my team,
Fabio B Leonardo

**Comment by nenadmilanovic** [comment]
Thank you very much for feedback Fabio.

We'll make it more understandable. @malizmaj
