### ISSUE TITLE
Getting current user ID not possible?

### ISSUE THREAD

**Issue by thecatontheflat** [clockify/clockify_api_docs#10]
Hey guys,
we are trying to make use of the Clockify API, I was hoping you could help us with something.

Is it possible to get the current user ID somehow? 
Use case — getting all time entries of the current user (the one who is requesting the API with their token).

Maybe it is also possible to do that without user ID?

**Comment by malizmaj** [comment]
Hi,

You can get this info using the log-in endpoint (currently, it's missing from the documentation but we'll add it soon):

`POST https://api.clockify.me/api/auth/token`

Request body:

```
{  
  "email":"my.login.email@company.com",
  "password":"mypassword"
}
```

Another way is to GET all users in a workspace and find your ID based on your email.

Hope that helps. Cheers!

**Comment by thecatontheflat** [comment]
Thank you for your reply @malizmaj 

We are relying on user token so we don't have email/password. 
Is it possible to get the user ID by the token only?

**Comment by malizmaj** [comment]
Sure, you can use this:

```POST https://api.clockify.me/api/auth/token/refresh```

Body: 

```{"refreshToken": "$YourTokenId"}```

**Comment by thecatontheflat** [comment]
Hey again @malizmaj 
I apologise for the confusion — I was referring to the API key.

Is it possible to get the user ID using the **API key** only?

**Comment by malizmaj** [comment]
Not really. But, we have this on our to-do so it'll be possible to get your user info with just your API key at some point in the future. Thanks for the feedback!

**Comment by m-horejsi** [comment]
How far is the future? 😄  I would appreciate if it was in few days..

**Comment by malizmaj** [comment]
Well, all I can say it's waaay down in our backlog (and our to-do and in-progress just keeps growing). So... that future isn't really near :)

**Comment by iLLiCiTiT** [comment]
Hi! Really need to implement this feature or give me another possibility to get user's permissions than using "/workspaces/${workspaceId}/users/${userId}/permissions"

At this moment if I want to get user's "permission to create project" I have to try create project, store success bool and delete project if success was true.
Is there better way only with API Key?

**Comment by malizmaj** [comment]
You can use `GET /workspaces/{workspaceId}/users` to get IDs of users (and see who's is and isn't admin), and then `GET /workspaces/{workspaceId}` [link](https://clockify.github.io/clockify_api_docs/#operation--workspaces--workspaceId--get) to see whether regular users can create projects or not.

**Comment by iLLiCiTiT** [comment]
I have access only to API Key. I don't have access to email/username/name/ and so on, so how can I find out which userId belogs to the specific user?

**Comment by malizmaj** [comment]
Run `GET /workspaces/{workspaceId}/users` and you'll get a list of all the users in that particular workspace.

**Comment by iLLiCiTiT** [comment]
Yes, I know and once more time: How I am able to recognize which user information belongs to specific API Key?

**Comment by malizmaj** [comment]
API keys are private. Workspace owner/admin can't see API keys of their people in their workspace (eg. you can have your own workspace where you track time for your company, and when a client invites you to their workspace, just because you're a members doesn't mean they can access your key and your private data from personal workspace)

**Comment by iLLiCiTiT** [comment]
So, sum up: I'm not able to get permissions of user only with API key.

I have access **only** to API Key of user, so I don't have access to *userId* because I'm not able to identify which item from ```GET /workspaces/{workspaceId}/users``` belongs to API Key.
That's the reason why I'm not able to get user's permission from ```"/workspaces/${workspaceId}/users/${userId}/permissions"```.
So only way to get user's permission to create project is try to create project, store result and if result was successful delete created project :)

**Comment by malizmaj** [comment]
I'm afraid there's no simple way to do this. You can:

- Check if regular users can create projects in that workspace `GET /workspaces/{workspaceId}`
- Get a list of all users and their IDs `GET /workspaces/{workspaceId}/users`
- For each user, see if they're admin or not `GET /workspaces/${workspaceId}/users/${userId}/permissions`

**Comment by iLLiCiTiT** [comment]
I see. I think ability to get permissions (or userId - should have more benefits to use at multiple places) only with API Key is actually really important for rest API workaround.
Because you didn't gave me another option I have to continue with my current method.
Have a nice day

**Comment by m-horejsi** [comment]
I vote for API which will return me userId when I have API key.

**Comment by alexriziy** [comment]
> I vote for API which will return me userId when I have API key.
+1

**Comment by CookiePLMonster** [comment]
+1 on that. I am looking into the solution where I can get user's time entries using **only** an API key in order to be able to resume the last entry. Thus to be able to do that, I need to be able to obtain the user ID of token's owner. Having no option like this is kind of a deal breaker for me.

**Comment by malizmaj** [comment]
We're working on stable v1.0 API. It's not yet completed and documented, but you might find this useful:

Header: `X-Auth-Token` or `X-Api-Key`

`GET /v1/user`

RESPONSE:

```
{
   "id": "5bfd36a4b0798777049513e2",
   "email": "jackie.brown@company.com",
   "name": "Jackie Brown",
   "memberships": [
       {
           "userId": "5bfd36a4b0798777049513e2",
           "hourlyRate": null,
           "targetId": "5bfd36c4b0798777049512e3",
           "membershipType": "WORKSPACE",
           "membershipStatus": "ACTIVE"
       },
       {
           "userId": "5bfd36a4b0798777049513e2",
           "hourlyRate": null,
           "targetId": "5a775388b079876a9beb34e8",
           "membershipType": "USERGROUP",
           "membershipStatus": "ACTIVE"
       }
   ],
   "profilePicture": "https://s3.eu-central-1.amazonaws.com/clockify/no-user-image.png",   "activeWorkspace": "5bfd36c4b0798777049512e3",
   "defaultWorkspace": "5bfd36c4b0798777049512e3",
   "settings": {
       "weekStart": "MONDAY",
       "timeZone": "Europe/Belgrade",
       "timeFormat": "HOUR24",
       "dateFormat": "MM/DD/YYYY",
       "sendNewsletter": true,
       "weeklyUpdates": false,
       "longRunning": true,
       "summaryReportSettings": {
           "group": "Project",
           "subgroup": "Time Entry"
       },
       "isCompactViewOn": false,
       "dashboardSelection": "ME",
       "dashboardViewType": "BILLABILITY",
       "dashboardPinToTop": false,
       "timeTrackingManual": false
   },
   "status": "ACTIVE"
}
```

**Comment by CookiePLMonster** [comment]
Very nice, thank you! A few questions:

1) Is this specific query available yet?
2) `X-Auth-Token` is not documented yet, but is it the token returned from current API's `POST /auth/token` under `"token"`?

**Comment by malizmaj** [comment]
Yes to both. We've just launched the endpoint yesterday. For `X-Auth-Token`, you can use the token you get from `POST /auth/token`

**Comment by CookiePLMonster** [comment]
I had a chance to test it and it's confirmed working! Thank you, it'll be very useful.

**Comment by m-horejsi** [comment]
Nice!

**Comment by thecatontheflat** [comment]
Thanks!

**Comment by iLLiCiTiT** [comment]
I have issue with unicode strings in response because of python so I'm unable to test it right now, but many thanks!
