### ISSUE TITLE
Accessing other user time entries

### ISSUE THREAD

**Issue by seantitmarsh** [clockify/clockify_api_docs#12]
Hi,

I'm trying to pull down via the API a full list of all users (~10 people) and their time entries. Getting the users and their ids isn't an issue, but when I try to request time entries for [other members of the team](https://clockify.github.io/clockify_api_docs/#operation--workspaces--workspaceId--timeEntries-user--userId--dateRange--get), I'm being given a 403 error:

Request:
```
user = USER_ID
times = {'start': '2019-03-10T14:00:00.000Z', 'end': '2019-03-17T13:59:59.999Z'}
request = requests.post(ENDPOINT + WORKSPACE + '/timeEntries/user/' + user + '/entriesInRange', headers={'X-Api-Key': APIKEY}, json=times)
entries = request.json()
```

Response:
`{"message":"Full authentication is required to access this resource","code":1000}`

Accessing my own entries, with my API key, is returning correctly. I've tried with both an Admin and Owner API key, which will return their own times, but there's no luck getting the other users times. 

The workspace is on the "Plus" subscription.

Thanks!

**Comment by malizmaj** [comment]
It's the limitation of the API. That endpoint is mainly used for POST request for adding time for another user (available if you're an admin on a premium workspace).

To get someone's entries, it's best to use the Summary report endpoint and pass user ID(s) in filter.

**Comment by seantitmarsh** [comment]
No worries, I'll look at doing it that way. Thanks.
