### ISSUE TITLE
Get personal time entries in date range - 404

### ISSUE THREAD

**Issue by m-horejsi** [clockify/clockify_api_docs#13]
Hi,

I'm getting "404 - Not Found" error when calling [Get personal time entries in date range](https://clockify.github.io/clockify_api_docs/#operation--workspaces--workspaceId--timeEntries-user--userId--dateRange--get) for request which used to work few weeks ago. Could you check it?

Method:
POST /workspaces/{workspaceId}/timeEntries/user/{userId}/entriesInRange

When I try to call GET {workspaceId}/timeEntries/user/{userId}, I will get HTTP status 200 and expected response

**Comment by malizmaj** [comment]
Hi, that method requires "start" and "end" values in the POST method. To GET your personal entries, you can use GET /workspaces/{workspaceId}/timeEntries/user/{userId}
 https://clockify.github.io/clockify_api_docs/#operation--workspaces--workspaceId--timeEntries-user--userId--get

Note that this is deprecated API and is prone to breaking changes. For that reason, it's best to use the stable API, which you can find here: https://clockify.me/developers-api

**Comment by m-horejsi** [comment]
Of course I'm sending the start and end in body - the request used to work few weeks ago.
`{
    "start": "2019-02-01T00:00:00.000Z",
    "end": "2019-02-15T18:00:00.000Z"
}`
Is this method (Get personal time entries in date range) in new API? Because I can't see the documentation for this method in new developers API

**Comment by malizmaj** [comment]
Sure, you can use the "[Find time entries for user on workspace](https://clockify.me/developers-api#operation--v1-workspaces--workspaceId--user--userId--time-entries-get)" endpoint, and use the `start` and `end` parameters in the query itself

**Comment by m-horejsi** [comment]
But this method can be uses only if you have WORKSPACE_OWN or WORKSPACE_ADMIN permissions. But I don't have these permissions.. I'm ordinary user and want to see my entries for given time period..

**Comment by malizmaj** [comment]
True, but only if you're requesting other people's entries from the workspace AND don't have the permission. You can still get your own entries this way. You just need the workspace and your user ID, which you can get with "[Get currently logged in user's info](https://clockify.me/developers-api#operation--v1-user-get)"
