### ISSUE TITLE
Possible to filter time entries by date range?

### ISSUE THREAD

**Issue by eimajenthat** [clockify/clockify_api_docs#2]
Love the app.  Just doing some research to see if I can adapt it to use in my workflows.

I see in the docs how we can get a list of time entries filtered by project and by user, which is excellent.  But is there a way to get time entries filtered by date range?

In Toggl, you do this with the reporting API, but it doesn't look like the reports endpoints return actual time entry data in your API.  Unless I'm mistaken?

**Comment by malizmaj** [comment]
Yes, there's the endpoint for getting time entries in a range. We've just updated the documentation, check out [the diff](https://github.com/clockify/clockify_api_docs/commit/2a1b2dcbfd9f6d949058ce5f41d60d4b051a5950) to see it. Hope that helps!

**Comment by eimajenthat** [comment]
Perfect!!!  Thanks so much.

**Comment by consulthys** [comment]
How about finding all entries in a given time range for all users? For instance, how do I get all entries for a given month for all users? Right now, I have to:
 1. retrieve all users from the workspace
 2. then for each user, retrieve the time entries in the given time range

That's a lot of calls for something that would seem pretty simple. I'm basically looking for the equivalent Clockify API call of what the [Toggl API is offering](https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#get-time-entries-started-in-a-specific-time-range). This is the only thing that prevents me from migrating right now.

**Comment by jovanadragojlovic** [comment]
@consulthys Unfortunately, there's no direct endpoint for getting entries in range for all users.
But you can check out the summary report endpoint. It's response contains "timeEntries". You can set parameters "startDate" and "endDate" to any dates you want, and it will give you all entries from all users in that date range. Plus you can filter by userIds if you wish. Don't bother parameter "zoomLevel", just set it to "week".
https://clockify.github.io/clockify_api_docs/#tag-Summary-report 

Hope this helps!
Cheers!

**Comment by consulthys** [comment]
Thanks @jovanadragojlovic for getting back to me. 
In the meantime, I've landed exactly on that endpoint and realized it should serve my needs perfectly.
