### ISSUE TITLE
How to get all Clockify Users within a Workspace

### ISSUE THREAD

**Issue by ChaddPortwine** [clockify/clockify_api_docs#3]
I would like to use the Clockify API to pull user emails from Clockify. I am making requests and receiving data with the API. What is the best way to get user data?

I can use `workspaces/{workspaceId}/userGroups` and then sort/filter through all the user groups to pull out user IDs, then find emails based on IDs. But what if a team member is not assigned to a group.

Maybe there is a better way to get the ID and eventually the email of all users within a Workspace?

Thanks!

**Comment by ljsimintt** [comment]
You can use `https://api.clockify.me/api/workspaces/%7BworkspaceID%7D/users`

Check out the example:
https://clockify.github.io/clockify_api_docs/#operation--workspaces--workspaceId--users-get

**Comment by cedomirm1990** [comment]
Hi, 
You can get all users within a workspace on workspace endpoint under "Find all users on workspace".
You can see that on https://clockify.github.io/clockify_api_docs/#operation--workspaces--workspaceId--users-get.

**Comment by ljsimin** [comment]
You can use `https://api.clockify.me/api/workspaces/%7BworkspaceID%7D/users`

Check out the example:
https://clockify.github.io/clockify_api_docs/#operation--workspaces--workspaceId--users-get

**Comment by ChaddPortwine** [comment]
Yes, that's it! Thank you for pointing me to it in the documentation.
