### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by arielcamus** [clockify/clockify_api_docs#6]
Hi Clockify team,

If I try inviting a user with an email address that contains the `+` character, the API returns the following error:

```
{
    "timestamp": "2019-01-03T19:09:12.126+0000",
    "status": 400,
    "error": "Bad Request",
    "exception": "com.clockify.domain.model.domain.DomainNotValidException",
    "message": "No message available",
    "path": "/workspaces/{workspace_id}/users"
}
```

Here is an example:
```
{
	"emails":[
		"name+something@domain.com"
	]
	
}
```

I've tried URL encoding it first and it returns the same error:

```
{
	"emails":[
		"name%2Bsomething%40domain.com"
	]
	
}
```

Any idea of why?

**Comment by malizmaj** [comment]
Hi Ariel, the domains that contain the plus sign are automatically invalid on the back-end. This was used to prevent people from spamming the registration in the past, but is now no longer relevant. We'll disable the validation for this.

**Comment by malizmaj** [comment]
Fixed. Emails with + should be valid now.
