### ISSUE TITLE
time entry API request contains wrong hourlyRate

### ISSUE THREAD

**Issue by TKlerx** [clockify/clockify_api_docs#8]
Hi there,

I am using the API to retrieve all time entries. It works so far except that the time entry itself (I do not mean the hourly rate of the user/project/workspace) does not contain an hourly rate but always "null". I would expect it to contain the hourly rate as stated in the docs (see https://clockify.github.io/clockify_api_docs/#definition-TimeEntriesListDto )
I double checked the UI and we have set workspace/project/user/project-team hourly rates.

The output I get is:
``` 
...
 'project': {'id': '5c34a26bb079874ebdddb3e7',
  'name': 'Finance Analytics',
  'hourlyRate': {'amount': 2000, 'currency': 'EUR'},
  'clientId': '5c3492f9b079874ebddd5cd1',
  'workspaceId': '5c0e4137b079876430529434',
  'billable': True,
...
'timeInterval': {'start': '2019-01-22T08:00:36.844Z',
  'end': '2019-01-22T08:30:36.844Z',
  'duration': 'PT30M'},
 'workspaceId': '5c0e4137b079876430529434',
 'totalBillable': None,
 'hourlyRate': None,
 'isLocked': False,
 'projectId': '5c34a26bb079874ebdddb3e7'}
...
```

Best,
Timo

**Comment by malizmaj** [comment]
Hm, it seems like the link you've included points to a definition that doesn't return hourly rate. Could you provide us with more information? Also, is there anything in particular you need that we can help you find?

**Comment by TKlerx** [comment]
Actually, I used the API docs and sent a pretty normal request to https://api.clockify.me/api/workspaces/{workspaceId}/timeEntries/?page=1
According to the API docs ( https://clockify.github.io/clockify_api_docs/#tag-Time-entry ) I should get the hourly rate in the result set.

Do you need additional information?

**Comment by malizmaj** [comment]
I see. The API has some legacy code that needs to be cleaned up. This request shouldn't return hourly rates. We'll remove them from response once we find some time.

In the meantime, to get the hourly rates, you can use the POST /workspaces/{workspaceId}/reports/summary/

Hope that helps. Cheers!

**Comment by TKlerx** [comment]
How to access the POST api? I did not find anything related in the documentation. The time entries shall be kept private, of course.
I get 
```
{
    "message": "Full authentication is required to access this resource",
    "code": 1000
}
```

**Comment by malizmaj** [comment]
API returns time entries for the filters you've specified (eg. if you put 2017 for startTime and 2018 for endTime, you'll get all the entries as long as you don't use any other filters).

Regarding the hourlyRate, we have several levels of hourly rate priorities, which we include with the time entry. The schema goes like this:

```
1. if project.userMemberhip.hourlyRate exists return project.userMemberhip.hourlyRate
2. if project.hourlyRate exists return project.hourlyRate
3. if workspace.userMembership.hourlyRate exists return workspace.userMembership.hourlyRate
4. if workspace.hourlyRate exists return workspace.hourlyRate
```

**Comment by TKlerx** [comment]
I am exactly looking for this schema as result in the time entry.
In my example, the project has an hourly rate, but the resulting time entry does not have one. 

So how do I get the priorities you mentioned?

**Comment by malizmaj** [comment]
When the time entry is set as non-billable, the hourly rate is always zero. When the entry is marked as billable, the hourly rate you get depends on the schema. For example, if you have some hourly rate on a project and the workspace rate, and the entry has the project attached, you'll get project's hourly rate (as according to the schema).

**Comment by TKlerx** [comment]
Somehow, I always get hourly rate as ``null`` even though the time entry is billable. That's why I opened this issue. Maybe, we can set up a meeting and I can share my screen and show you the problem.

**Comment by malizmaj** [comment]
Hm, I think we'll need more info on this. Could you send us an email at support@clockify.me with the example of request you're sending, your API and workspace key, and info on the expected vs actual result? Thanks!
